// openframe/services/openframe-ui/src/components/MainLayout.vue
<template>
  <div class="layout-container" :data-theme="isDark ? 'dark' : 'light'">
    <nav class="navbar">
      <div class="navbar-start">
        <OFButton icon="pi pi-bars" text rounded @click="toggleMenu" class="menu-button" />
        <div class="brand">
          <div class="brand-name">
            <span class="brand-title">Open<span class="brand-highlight">Frame</span></span>
            <span class="brand-divider">@</span>
            <span class="brand-section">Dashboard</span>
          </div>
        </div>
      </div>
      <div class="navbar-end">
        <ThemeToggle />
        <OFButton 
          icon="pi pi-user" 
          text 
          rounded 
          class="mr-2" 
          @click="router.push('/profile')"
        />
        <OFButton icon="pi pi-power-off" text rounded severity="secondary" @click="handleLogout" />
      </div>
    </nav>

    <Sidebar 
      v-model:visible="menuVisible" 
      :modal="true" 
      :showCloseIcon="false"
      class="main-sidebar"
      :pt="{
        root: { class: isDark ? 'dark-theme' : 'light-theme' },
        content: { class: isDark ? 'dark-theme' : 'light-theme' }
      }"
    >
      <template #header>
        <div class="sidebar-header">
          <OFButton 
            icon="pi pi-times" 
            text 
            rounded 
            @click="menuVisible = false"
            class="close-button"
          />
        </div>
      </template>
      <div class="menu">
        <template v-for="item in menuItems" :key="item.path || item.label">
          <!-- Regular menu item -->
          <router-link 
            v-if="!item.children && item.path"
            :to="item.path"
            class="menu-item"
            :class="{ active: route.path === item.path }"
            @click="menuVisible = false"
          >
            <i :class="item.icon"></i>
            <span>{{ item.label }}</span>
          </router-link>
          
          <!-- Menu item with children -->
          <div v-else class="submenu">
            <div 
              class="menu-item submenu-header" 
              @click="toggleSubmenu(item)"
              :class="{ expanded: expandedMenus.includes(item.label) }"
            >
              <div class="submenu-header-content">
                <i :class="item.icon"></i>
                <span>{{ item.label }}</span>
              </div>
              <i class="pi pi-chevron-down submenu-arrow"></i>
            </div>
            <div 
              class="submenu-content" 
              :class="{ expanded: expandedMenus.includes(item.label) }"
            >
              <template v-for="child in item.children" :key="child.path || child.label">
                <!-- Regular child item -->
                <router-link 
                  v-if="!child.children && child.path"
                  :to="child.path"
                  class="menu-item submenu-item"
                  :class="{ active: route.path.startsWith(child.path) }"
                  @click="menuVisible = false"
                >
                  <i :class="child.icon"></i>
                  <span>{{ child.label }}</span>
                </router-link>
                
                <!-- Nested submenu -->
                <div v-else class="submenu nested">
                  <div 
                    class="menu-item submenu-header" 
                    @click="toggleSubmenu(child)"
                    :class="{ expanded: expandedMenus.includes(child.label) }"
                  >
                    <div class="submenu-header-content">
                      <i :class="child.icon"></i>
                      <span>{{ child.label }}</span>
                    </div>
                    <i class="pi pi-chevron-down submenu-arrow"></i>
                  </div>
                  <div 
                    class="submenu-content" 
                    :class="{ expanded: expandedMenus.includes(child.label) }"
                  >
                    <router-link 
                      v-for="grandChild in child.children"
                      :key="grandChild.path"
                      :to="grandChild.path || '/'"
                      class="menu-item submenu-item nested"
                      :class="{ active: route.path === grandChild.path }"
                      @click="menuVisible = false"
                    >
                      <i :class="grandChild.icon"></i>
                      <span>{{ grandChild.label }}</span>
                    </router-link>
                  </div>
                </div>
              </template>
            </div>
          </div>
        </template>
      </div>
    </Sidebar>

    <div class="layout-content">
      <main class="main-content">
        <slot></slot>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { OFButton } from '@/components/ui';
import Sidebar from 'primevue/sidebar';
import { useAuthStore } from '@/stores/auth';
import ThemeToggle from './ThemeToggle.vue'
import { storeToRefs } from 'pinia'
import { useThemeStore } from '@/stores/themeStore'

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const menuVisible = ref(false);
const themeStore = useThemeStore()
const { isDark } = storeToRefs(themeStore)
const expandedMenus = ref<string[]>(['Integrated Tools']);

interface MenuItem {
  label: string;
  icon: string;
  path?: string;
  children?: MenuItem[];
}

const menuItems: MenuItem[] = [
  {
    label: 'Dashboard',
    icon: 'pi pi-home',
    path: '/dashboard'
  },
  {
    label: 'Devices',
    icon: 'pi pi-desktop',
    path: '/devices'
  },
  {
    label: 'Logs',
    icon: 'pi pi-list',
    path: '/logs'
  },
  {
    label: 'Integrated Tools',
    icon: 'pi pi-wrench',
    children: [
      {
        label: 'Remote Monitoring & Management',
        icon: 'pi pi-server',
        path: '/rmm'
      },
      {
        label: 'Remote Access and Control',
        icon: 'pi pi-desktop',
        path: '/rac'
      },
      {
        label: 'Mobile Device Management',
        icon: 'pi pi-mobile',
        path: '/mdm'
      }
    ]
  },
  {
    label: 'Infrastructure',
    icon: 'pi pi-sitemap',
    path: '/tools'
  },
  {
    label: 'Monitoring',
    icon: 'pi pi-chart-line',
    path: '/monitoring'
  },
  {
    label: 'Settings',
    icon: 'pi pi-cog',
    path: '/settings'
  },
  {
    label: 'SSO Configuration',
    icon: 'pi pi-key',
    path: '/sso'
  },
  {
    label: 'API Keys',
    icon: 'pi pi-shield',
    path: '/api-keys'
  }
];

const toggleSubmenu = (item: MenuItem) => {
  const index = expandedMenus.value.indexOf(item.label);
  if (index === -1) {
    expandedMenus.value.push(item.label);
  } else {
    expandedMenus.value.splice(index, 1);
  }
};

const toggleMenu = () => {
  menuVisible.value = !menuVisible.value;
};

const handleLogout = async () => {
  try {
    await authStore.logout();
    router.push('/login');
  } catch (error) {
    console.error('Logout error:', error);
    // Even if logout fails, redirect to login
    router.push('/login');
  }
};
</script>

<style scoped>
.layout-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

:deep(.dark-theme) {
  background: var(--surface-card) !important;
  color: var(--text-color) !important;
}

:deep(.light-theme) {
  background: var(--surface-card) !important;
  color: var(--text-color) !important;
}

.navbar {
  padding: 0.75rem 2rem;
  border-bottom: 1px solid var(--surface-border);
  background: var(--surface-card);
  display: flex;
  justify-content: space-between;
  align-items: center;
  z-index: 1000;
}

.menu-button {
  display: flex;
  align-items: center;
  justify-content: center;
}

.layout-content {
  flex: 1;
  display: flex;
  background: var(--surface-ground);
}

:deep(.main-sidebar) {
  .p-sidebar {
    @media screen and (min-width: 768px) {
      width: 250px;
    }
    @media screen and (max-width: 767px) {
      width: 100%;
    }
  }

  .p-sidebar-header {
    display: block !important;
    padding: 0.75rem 1rem;
    border-bottom: 1px solid var(--surface-border);
  }

  .p-sidebar-content {
    padding: 0;
  }
}

.menu {
  display: flex;
  flex-direction: column;
  padding: 1.5rem 1rem;
  gap: 0.5rem;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem 1rem;
  border-radius: var(--border-radius);
  color: var(--text-color-secondary);
  text-decoration: none;
  transition: all 0.2s ease;
}

.menu-item:hover {
  background: var(--surface-hover);
  color: var(--text-color);
}

.menu-item.active {
  background: var(--yellow-500);
  color: var(--surface-900);
  font-weight: 600;
}

.menu-item i {
  font-size: 1.25rem;
  color: inherit;
}

.main-content {
  flex: 1;
  padding: 1.5rem;
  overflow-y: auto;
}

/* Existing navbar styles... */
.navbar-start {
  display: flex;
  align-items: center;
  gap: 2rem;
}

.navbar-end {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.brand {
  display: flex;
  align-items: center;
}

.brand-name {
  font-size: 1.25rem;
  font-weight: 600;
  display: inline-flex;
  align-items: baseline;
}

.brand-title {
  font-family: 'Ubuntu', sans-serif;
  letter-spacing: -0.005em;
  white-space: nowrap;
}

.brand-highlight {
  font-family: 'Ubuntu', sans-serif;
  color: var(--primary-color);
}

.brand-divider {
  font-family: var(--font-family);
  color: var(--text-color-secondary);
  margin: 0 0.3em;
  font-weight: normal;
}

.brand-section {
  font-family: var(--font-family);
  color: var(--text-color-secondary);
  font-size: 0.875rem;
  font-weight: normal;
}

@media screen and (max-width: 767px) {
  .navbar {
    padding: 0.75rem 1rem;
  }

  .brand-section {
    display: none;
  }
}

.sidebar-header {
  display: flex;
  justify-content: flex-end;
  padding: 0.5rem;
}

.close-button {
  width: 2.5rem;
  height: 2.5rem;
}

:deep(.close-button) {
  .p-button-icon {
    font-size: 1rem;
  }

  &.p-button {
    padding: 0.5rem;
  }
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.theme-indicator {
  font-size: 0.875rem;
  color: var(--text-color-muted);
  margin-right: 1rem;
}

.submenu {
  display: flex;
  flex-direction: column;
}

.submenu-header {
  justify-content: space-between;
  cursor: pointer;
}

.submenu-header-content {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex: 1;
}

.submenu-arrow {
  transition: transform 0.2s ease;
  font-size: 0.875rem;
}

.submenu-header.expanded .submenu-arrow {
  transform: rotate(-180deg);
}

.submenu-content {
  display: none;
  padding-left: 1rem;
}

.submenu-content.expanded {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.submenu-item {
  padding-left: 2rem;
}

.submenu.nested {
  margin-left: -1rem;
}

.submenu-item.nested {
  padding-left: 3rem;
}

.menu-item.submenu-header {
  margin: 0;
  padding-right: 1rem;
}

.menu-item.submenu-header:hover {
  background: var(--surface-hover);
  color: var(--text-color);
}

.menu-item.submenu-header.expanded {
  background: var(--surface-hover);
  color: var(--text-color);
}

.menu-item.submenu-item.active {
  background: var(--yellow-500);
  color: var(--surface-900);
  font-weight: 600;
}
</style>

// openframe/services/openframe-frontend/src/components/layout/MainLayout.tsx
import { ReactNode, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { 
  Button, 
  Sheet,
  SheetContent,
  SheetTrigger,
  SheetHeader,
  SheetTitle,
  SheetClose
} from '@flamingo/ui-kit/components/ui';
import { 
  MenuIcon,
  UserIcon,
  SunIcon,
  MoonIcon
} from '@flamingo/ui-kit/components/icons';
import { cn } from '@flamingo/ui-kit/utils';
import { useAuthStore } from '@/stores/auth';
import { useTheme } from '@/hooks/useTheme';

interface MenuItem {
  label: string;
  path?: string;
  children?: MenuItem[];
}

interface MainLayoutProps {
  children: ReactNode;
}

export const MainLayout = ({ children }: MainLayoutProps) => {
  const location = useLocation();
  const navigate = useNavigate();
  const authStore = useAuthStore();
  const { theme, toggleTheme } = useTheme();
  const [menuOpen, setMenuOpen] = useState(false);
  const [expandedMenus, setExpandedMenus] = useState<string[]>(['Integrated Tools']);

  const menuItems: MenuItem[] = [
    {
      label: 'Dashboard',
      path: '/dashboard'
    },
    {
      label: 'Devices',
      path: '/devices'
    },
    {
      label: 'Integrated Tools',
      children: [
        {
          label: 'Remote Monitoring & Management',
          path: '/rmm'
        },
        {
          label: 'Remote Access and Control',
          path: '/rac'
        },
        {
          label: 'Mobile Device Management',
          path: '/mdm'
        }
      ]
    },
    {
      label: 'Infrastructure',
      path: '/tools'
    },
    {
      label: 'Monitoring',
      path: '/monitoring'
    },
    {
      label: 'Settings',
      path: '/settings'
    },
    {
      label: 'SSO Configuration',
      path: '/sso'
    },
    {
      label: 'API Keys',
      path: '/api-keys'
    }
  ];

  const toggleSubmenu = (label: string) => {
    setExpandedMenus(prev => 
      prev.includes(label) 
        ? prev.filter(l => l !== label)
        : [...prev, label]
    );
  };

  const handleLogout = async () => {
    try {
      await authStore.logout();
      navigate('/login');
    } catch (error) {
      console.error('Logout error:', error);
      navigate('/login');
    }
  };

  const renderMenuItem = (item: MenuItem, level = 0) => {
    const isActive = item.path && location.pathname.startsWith(item.path);
    const isExpanded = expandedMenus.includes(item.label);
    const hasChildren = item.children && item.children.length > 0;

    if (hasChildren) {
      return (
        <div key={item.label} className="mb-1">
          <button
            onClick={() => toggleSubmenu(item.label)}
            className={cn(
              "w-full flex items-center justify-between gap-3 px-3 py-2 rounded-md text-sm font-medium transition-colors",
              "hover:bg-ods-bg-subtle hover:text-ods-text-primary",
              "text-ods-text-secondary",
              isExpanded && "bg-ods-bg-subtle text-ods-text-primary"
            )}
          >
            <span>{item.label}</span>
            <span 
              className={cn(
                "text-xs transition-transform inline-block",
                isExpanded && "rotate-180"
              )}
            >
              ▼
            </span>
          </button>
          {isExpanded && item.children && (
            <div className="mt-1 ml-4">
              {item.children.map(child => renderMenuItem(child, level + 1))}
            </div>
          )}
        </div>
      );
    }

    return (
      <Link
        key={item.path}
        to={item.path!}
        onClick={() => setMenuOpen(false)}
        className={cn(
          "flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium transition-colors mb-1",
          level > 0 && "ml-4",
          isActive
            ? "bg-ods-accent text-ods-bg-primary font-semibold"
            : "text-ods-text-secondary hover:bg-ods-bg-subtle hover:text-ods-text-primary"
        )}
      >
        <span>{item.label}</span>
      </Link>
    );
  };

  return (
    <div className="min-h-screen flex flex-col bg-ods-bg-primary">
      {/* Navbar */}
      <nav className="border-b border-ods-border bg-ods-card">
        <div className="px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-4">
              <Sheet open={menuOpen} onOpenChange={setMenuOpen}>
                <SheetTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="lg:hidden"
                  >
                    <MenuIcon className="h-5 w-5" />
                  </Button>
                </SheetTrigger>
                <SheetContent side="left" className="w-80 p-0">
                  <SheetHeader className="border-b border-ods-border px-6 py-4">
                    <div className="flex items-center justify-between">
                      <SheetTitle className="text-lg font-semibold">Navigation</SheetTitle>
                      <SheetClose asChild>
                        <Button variant="ghost" size="icon" className="h-8 w-8">
                          <span className="text-lg">×</span>
                        </Button>
                      </SheetClose>
                    </div>
                  </SheetHeader>
                  <div className="px-4 py-6">
                    <nav className="space-y-1">
                      {menuItems.map(item => renderMenuItem(item))}
                    </nav>
                  </div>
                </SheetContent>
              </Sheet>
              
              <div className="flex items-center">
                <span className="text-xl font-bold">
                  Open<span className="text-ods-accent">Frame</span>
                </span>
                <span className="text-ods-text-secondary mx-2">@</span>
                <span className="text-ods-text-secondary text-sm">Dashboard</span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="icon"
                onClick={toggleTheme}
              >
                {theme === 'dark' ? (
                  <SunIcon className="h-5 w-5" />
                ) : (
                  <MoonIcon className="h-5 w-5" />
                )}
              </Button>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => navigate('/profile')}
              >
                <UserIcon className="h-5 w-5" />
              </Button>
              <Button
                variant="ghost"
                onClick={handleLogout}
                className="hidden sm:inline-flex"
              >
                Logout
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Desktop Sidebar */}
      <div className="flex flex-1">
        <aside className="hidden lg:flex lg:flex-shrink-0">
          <div className="flex w-64 flex-col">
            <div className="flex flex-1 flex-col overflow-y-auto bg-ods-card border-r border-ods-border">
              <nav className="flex-1 space-y-1 px-4 py-6">
                {menuItems.map(item => renderMenuItem(item))}
              </nav>
            </div>
          </div>
        </aside>

        {/* Main Content */}
        <main className="flex-1 overflow-y-auto">
          <div className="p-6">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};
